/**
 * Self-contained emoji dataset for the workspace icon picker.
 *
 * Kept in-repo (no third-party dependency) to honor the project's supply-chain
 * policy. Each entry has search keywords; grouped by category for browsing.
 */
export interface EmojiEntry {
  c: string; // the emoji character
  k: string; // space-separated search keywords
}

export interface EmojiCategory {
  name: string;
  items: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: "Tech & Infra",
    items: [
      { c: "🖥️", k: "computer desktop pc monitor server" },
      { c: "💻", k: "laptop computer dev mac notebook" },
      { c: "🖧", k: "network nodes" },
      { c: "🗄️", k: "filing cabinet server rack storage database archive" },
      { c: "💾", k: "floppy disk save storage backup" },
      { c: "💿", k: "disk cd dvd storage" },
      { c: "🧮", k: "abacus compute math calc" },
      { c: "🖲️", k: "trackball input" },
      { c: "⌨️", k: "keyboard input type terminal" },
      { c: "🖨️", k: "printer" },
      { c: "🪫", k: "battery low power" },
      { c: "🔋", k: "battery power energy" },
      { c: "🔌", k: "plug power electric connect" },
      { c: "📡", k: "satellite antenna signal network broadcast" },
      { c: "📶", k: "signal bars wifi network" },
      { c: "🛰️", k: "satellite space network" },
      { c: "🔭", k: "telescope observe monitor" },
      { c: "🧰", k: "toolbox tools devops" },
      { c: "🛠️", k: "tools hammer wrench build" },
      { c: "🔧", k: "wrench tool fix config" },
      { c: "⚙️", k: "gear settings config cog system" },
      { c: "🧲", k: "magnet attract" },
      { c: "🔒", k: "lock secure security ssl tls" },
      { c: "🔐", k: "lock key secure secret credentials" },
      { c: "🔑", k: "key access auth secret" },
      { c: "🗝️", k: "old key access vault" },
      { c: "🛡️", k: "shield security firewall protect" },
      { c: "🐛", k: "bug debug issue error" },
      { c: "🪲", k: "beetle bug debug" },
      { c: "🤖", k: "robot bot automation ai agent" },
      { c: "🧠", k: "brain ai ml intelligence" },
      { c: "📦", k: "package box container docker deploy module" },
      { c: "🧩", k: "puzzle plugin module extension piece" },
      { c: "🪛", k: "screwdriver tool fix" },
      { c: "📀", k: "dvd disk" },
    ],
  },
  {
    name: "Cloud & Net",
    items: [
      { c: "☁️", k: "cloud aws gcp azure storage" },
      { c: "⛅", k: "cloud partly sun weather" },
      { c: "🌩️", k: "storm cloud lightning thunder" },
      { c: "🌐", k: "globe web internet network world www" },
      { c: "🌍", k: "earth globe world europe africa region" },
      { c: "🌎", k: "earth globe world americas region" },
      { c: "🌏", k: "earth globe world asia region" },
      { c: "🧭", k: "compass navigate direction" },
      { c: "🗺️", k: "map region world" },
      { c: "📍", k: "pin location marker place" },
      { c: "📌", k: "pushpin pin mark" },
      { c: "🚀", k: "rocket launch deploy ship fast prod" },
      { c: "🛸", k: "ufo space" },
      { c: "✈️", k: "plane travel ship deploy" },
      { c: "🛬", k: "landing arrive deploy" },
      { c: "🔗", k: "link chain url connect" },
      { c: "⚡", k: "lightning fast bolt power electric speed" },
      { c: "🔥", k: "fire hot prod critical hotfix" },
      { c: "💥", k: "boom crash explosion incident" },
      { c: "🌊", k: "wave flood stream" },
    ],
  },
  {
    name: "Symbols & Status",
    items: [
      { c: "✅", k: "check done ok success pass green" },
      { c: "☑️", k: "checkbox done ok" },
      { c: "❎", k: "cross negative fail" },
      { c: "❌", k: "x cross fail error stop" },
      { c: "⛔", k: "no entry forbidden block stop" },
      { c: "🚫", k: "prohibited no block ban" },
      { c: "⚠️", k: "warning caution alert" },
      { c: "❗", k: "exclamation important alert" },
      { c: "❓", k: "question help unknown" },
      { c: "♻️", k: "recycle refresh cycle" },
      { c: "🔁", k: "repeat loop cycle retry" },
      { c: "🔄", k: "refresh sync reload cycle" },
      { c: "🆕", k: "new badge" },
      { c: "🆓", k: "free" },
      { c: "🔝", k: "top up" },
      { c: "⭐", k: "star favorite important" },
      { c: "🌟", k: "star sparkle special" },
      { c: "💫", k: "dizzy star sparkle" },
      { c: "✨", k: "sparkles shiny new magic" },
      { c: "🏁", k: "checkered flag finish done race" },
      { c: "🚩", k: "flag mark milestone" },
      { c: "🎯", k: "target goal aim bullseye" },
      { c: "📊", k: "bar chart stats metrics graph analytics" },
      { c: "📈", k: "chart up growth metrics trend" },
      { c: "📉", k: "chart down decline metrics" },
      { c: "🧪", k: "test tube experiment qa staging lab" },
      { c: "🔬", k: "microscope research analyze lab" },
      { c: "💡", k: "idea lightbulb tip insight" },
      { c: "🔔", k: "bell notify alert reminder" },
      { c: "📣", k: "megaphone announce broadcast" },
      { c: "♾️", k: "infinity loop forever" },
    ],
  },
  {
    name: "Objects",
    items: [
      { c: "📁", k: "folder directory files" },
      { c: "📂", k: "folder open directory" },
      { c: "🗂️", k: "dividers index organize" },
      { c: "📋", k: "clipboard tasks list" },
      { c: "📝", k: "memo notes write log" },
      { c: "📒", k: "ledger notebook" },
      { c: "📚", k: "books docs library" },
      { c: "📖", k: "book docs read" },
      { c: "🔖", k: "bookmark tag" },
      { c: "🏷️", k: "label tag" },
      { c: "📅", k: "calendar date schedule" },
      { c: "📆", k: "calendar date" },
      { c: "⏰", k: "alarm clock cron schedule time" },
      { c: "⏱️", k: "stopwatch timer perf" },
      { c: "⌛", k: "hourglass time wait" },
      { c: "🔦", k: "flashlight search inspect" },
      { c: "🔍", k: "search magnify find inspect zoom" },
      { c: "🔎", k: "search magnify find right" },
      { c: "💰", k: "money bag billing cost finance" },
      { c: "💳", k: "card payment billing" },
      { c: "🧾", k: "receipt invoice billing" },
      { c: "📧", k: "email mail message" },
      { c: "✉️", k: "envelope mail message" },
      { c: "📨", k: "incoming mail message" },
      { c: "🗃️", k: "card box archive" },
      { c: "🗳️", k: "ballot vote" },
      { c: "🧱", k: "brick wall block build infra" },
      { c: "🏗️", k: "construction build wip staging" },
      { c: "🪝", k: "hook webhook" },
      { c: "🧯", k: "extinguisher incident fire put out" },
      { c: "🛎️", k: "bell service desk support" },
    ],
  },
  {
    name: "Places",
    items: [
      { c: "🏠", k: "house home main local" },
      { c: "🏡", k: "home house garden" },
      { c: "🏢", k: "office building company corp" },
      { c: "🏬", k: "department store building" },
      { c: "🏭", k: "factory industrial prod" },
      { c: "🏦", k: "bank finance" },
      { c: "🏰", k: "castle fortress" },
      { c: "🗼", k: "tower" },
      { c: "🗽", k: "statue liberty us nyc" },
      { c: "⛩️", k: "shrine japan asia" },
      { c: "🌆", k: "city dusk skyline" },
      { c: "🌃", k: "city night" },
      { c: "🏙️", k: "cityscape skyline" },
      { c: "🏝️", k: "island isolated" },
      { c: "🏔️", k: "mountain peak high" },
      { c: "🌋", k: "volcano incident hot" },
      { c: "🗻", k: "fuji mountain japan" },
    ],
  },
  {
    name: "Faces & Fun",
    items: [
      { c: "😀", k: "smile happy face grin" },
      { c: "😎", k: "cool sunglasses chill" },
      { c: "🤓", k: "nerd geek glasses dev" },
      { c: "🥳", k: "party celebrate release" },
      { c: "😴", k: "sleep idle inactive zzz" },
      { c: "🤔", k: "thinking hmm question" },
      { c: "😵", k: "dizzy dead crash" },
      { c: "💀", k: "skull dead fatal crash error" },
      { c: "👻", k: "ghost spooky hidden" },
      { c: "👽", k: "alien" },
      { c: "🔮", k: "crystal ball predict future" },
      { c: "🎲", k: "dice random chance" },
      { c: "🎮", k: "game controller play" },
      { c: "🕹️", k: "joystick game retro" },
      { c: "🎨", k: "art palette design color" },
      { c: "🎭", k: "theater masks staging" },
      { c: "🧨", k: "firecracker boom" },
      { c: "🎉", k: "party celebrate launch release" },
      { c: "🎁", k: "gift present release" },
      { c: "🏆", k: "trophy win prod champion" },
      { c: "🥇", k: "gold medal first prod primary" },
      { c: "🎓", k: "graduation learn academy" },
    ],
  },
  {
    name: "Animals & Nature",
    items: [
      { c: "🐧", k: "penguin linux tux" },
      { c: "🐳", k: "whale docker kubernetes container" },
      { c: "🐋", k: "whale big docker" },
      { c: "🐬", k: "dolphin mysql" },
      { c: "🐘", k: "elephant php postgres database" },
      { c: "🦫", k: "beaver go gopher build" },
      { c: "🦀", k: "crab rust" },
      { c: "🐍", k: "snake python" },
      { c: "🐹", k: "hamster go gopher" },
      { c: "🐙", k: "octopus github octocat" },
      { c: "🐈", k: "cat" },
      { c: "🐱", k: "cat face kitten" },
      { c: "🐶", k: "dog puppy" },
      { c: "🦊", k: "fox firefox" },
      { c: "🦁", k: "lion brave" },
      { c: "🐯", k: "tiger" },
      { c: "🐻", k: "bear" },
      { c: "🐼", k: "panda" },
      { c: "🦉", k: "owl night monitor watch" },
      { c: "🦅", k: "eagle fast" },
      { c: "🐝", k: "bee busy hive worker" },
      { c: "🐞", k: "ladybug bug" },
      { c: "🌳", k: "tree branch nature green" },
      { c: "🌲", k: "evergreen tree pine" },
      { c: "🌵", k: "cactus desert" },
      { c: "🍀", k: "clover luck green" },
      { c: "🌱", k: "seedling new grow start" },
      { c: "🌸", k: "blossom flower pink" },
      { c: "🌺", k: "flower hibiscus" },
      { c: "🌈", k: "rainbow colorful" },
    ],
  },
  {
    name: "Food & Drink",
    items: [
      { c: "☕", k: "coffee cafe break dev" },
      { c: "🍵", k: "tea green" },
      { c: "🍺", k: "beer drink friday" },
      { c: "🍻", k: "beers cheers celebrate" },
      { c: "🍷", k: "wine drink" },
      { c: "🍕", k: "pizza food" },
      { c: "🍔", k: "burger food" },
      { c: "🌮", k: "taco food" },
      { c: "🍜", k: "noodles ramen food" },
      { c: "🍩", k: "donut food sweet" },
      { c: "🍪", k: "cookie sweet" },
      { c: "🎂", k: "cake birthday release" },
      { c: "🍎", k: "apple red fruit" },
      { c: "🍊", k: "orange fruit" },
      { c: "🍋", k: "lemon fresh" },
      { c: "🍓", k: "strawberry fruit" },
      { c: "🍇", k: "grapes fruit" },
      { c: "🌶️", k: "pepper hot spicy chili" },
      { c: "🧊", k: "ice cube cold cache freeze" },
      { c: "🍫", k: "chocolate sweet" },
    ],
  },
];

/** Flat list of all emojis (for dedup / fallback). */
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap(
  (c) => c.items,
);
